return {
	SchemaVersion = 3,
	AssetName = "Kaiju-I Bound Chimera",
	AssetId = "KAIJU-01-BOUND-CHIMERA",
	AssetClass = "Playable Kaiju Evolution",
	ModelName = "Kaiju_I_Bound_Chimera_GoldenMaster",
	PipelinePhase = 4,
	QualityGateA = "Approved",
	QualityGateB = "Pending",
	QualityGateC = "Pending",
	Evolution = {
		Stage = 1,
		StageCount = 5,
		Name = "Bound Chimera",
		Identity = "Embodied primal force: storm, volcanic pressure, and radioactive energy in an original animal form",
		Successor = "Storm Hunter",
		LineageAnchors = {"PredatorWedgeHead", "YellowEyes", "UprightBiped", "OpenBarrelChest", "LongPowerArms", "ShatteredStormShields", "ThreeForwardOneRearClaw"},
		ForbiddenStage1Traits = {"ShoulderArmor", "EvolvedHeadArmor", "CalderaChest", "CatastropheCrown"},
	},
	Anatomy = {
		Stance = "UprightDominantDigitigradeBiped",
		ForwardClawsPerFoot = 3,
		RearClawsPerFoot = 1,
		DorsalShieldCount = 7,
		ArmRule = "LongPowerfulFreeHangingToMidThighNeverGroundSupport",
		TorsoRule = "OpenMassiveBarrelChestNotHunched",
		LegRule = "ExtremelyThickLoadBearingDigitigradeNoThinJoints",
		FootRule = "BroadStablePredatoryFeet",
		Counterbalance = "VisibleSevenSegmentCylinderTail",
	},
	VisualLanguage = {
		Body = "Charcoal organic hide with restrained mineral pressure ridges",
		Eyes = "PureYellow",
		EnergySpectrum = "YellowToGreenOnly",
		Dorsals = "Angular asymmetrical shattered storm armor shields; never mushroom, shell, crystal, or simple spike",
		StageRead = "Primitive powerful first evolution; lineage is obvious but later-stage armor is absent",
	},
	PerformanceBudget = {
		MaxVisibleParts = 190,
		MaxGameplayHitboxes = 2,
		PermanentLights = 0,
		PermanentParticleEmitters = 0,
		PerPartScripts = 0,
	},
}
