return {
	SchemaVersion = 2,
	AssetName = "Kaiju-I Bound Chimera",
	AssetId = "KAIJU-01-BOUND-CHIMERA",
	AssetClass = "Playable Kaiju Evolution",
	ModelName = "Kaiju_I_Bound_Chimera_GoldenMaster",
	PipelinePhase = 4,
	QualityGateA = "Approved",
	QualityGateB = "Pending",
	QualityGateC = "Pending",
	Evolution = {
		Stage = 1,
		StageCount = 5,
		Name = "Bound Chimera",
		Identity = "Embodied primal force: storm, volcanic pressure, and radioactive energy in an original animal form",
		Successor = "Storm Hunter",
		LineageAnchors = {"WedgeHead", "YellowEyes", "UprightBiped", "ShatteredStormShields", "ThreeForwardOneRearClaw"},
	},
	Anatomy = {
		Stance = "UprightDominantDigitigradeBiped",
		ForwardClawsPerFoot = 3,
		RearClawsPerFoot = 1,
		DorsalShieldCount = 7,
		ArmRule = "ShortFreeHangingNeverGroundSupport",
		Counterbalance = "ShortOrganicStormRudder",
	},
	VisualLanguage = {
		Body = "Charcoal organic hide with limited mineral pressure armor",
		Eyes = "PureYellow",
		EnergySpectrum = "YellowToGreenOnly",
		Dorsals = "Angular asymmetrical shattered storm armor shields; never mushroom, shell, crystal, or simple spike",
	},
	PerformanceBudget = {
		MaxVisibleParts = 170,
		MaxGameplayHitboxes = 2,
		PermanentLights = 0,
		PermanentParticleEmitters = 0,
		PerPartScripts = 0,
	},
}
