-- Generated by tools/build_emberline.py; edit the generator, not this file.
-- Phase 4 only. No gameplay tag, HP, energy or live destruction hooks.
local Builder = {}
local Parts = {
 {"Site", "GroundSlab", 176, 1, 112, 0, -0.5, 0, 162, 162, 153, true},
 {"Site", "ResponseApron", 176, 0.08, 40, 0, 0.04, -36, 162, 162, 153, true},
 {"VehicleHall", "RearWall", 96, 38, 2, -36.0, 19.0, 51.0, 225, 222, 209, true},
 {"VehicleHall", "LeftWall", 2, 38, 62, -83.0, 19.0, 19.0, 225, 222, 209, true},
 {"VehicleHall", "RightWall", 2, 38, 62, 11.0, 19.0, 19.0, 225, 222, 209, true},
 {"VehicleHall", "Floor", 92, 1, 62, -36.0, 0.5, 19.0, 225, 222, 209, true},
 {"VehicleHall", "Roof", 96, 2, 64, -36.0, 39.0, 20.0, 57, 62, 65, true},
 {"VehicleHall", "FrontLintel", 96, 8, 2, -36.0, 34.0, -11.0, 225, 222, 209, true},
 {"VehicleHall", "Pier_01", 4.799999999999997, 30, 3, -81.6, 15.0, -10.5, 225, 222, 209, true},
 {"VehicleHall", "Pier_02", 4.799999999999997, 30, 3, -58.800000000000004, 15.0, -10.5, 225, 222, 209, true},
 {"VehicleHall", "Pier_03", 4.799999999999997, 30, 3, -36.0, 15.0, -10.5, 225, 222, 209, true},
 {"VehicleHall", "Pier_04", 4.800000000000001, 30, 3, -13.199999999999994, 15.0, -10.5, 225, 222, 209, true},
 {"VehicleHall", "Pier_05", 4.800000000000001, 30, 3, 9.600000000000003, 15.0, -10.5, 225, 222, 209, true},
 {"BayDoor_01", "LowerPanel", 18.0, 8, 0.9000000000000004, -70.2, 4.0, -11.45, 177, 31, 40, true},
 {"BayDoor_01", "WindowBand", 18.0, 3, 0.5999999999999996, -70.2, 9.5, -11.399999999999999, 39, 65, 71, true},
 {"BayDoor_01", "UpperPanel", 18.0, 19, 0.9000000000000004, -70.2, 20.5, -11.45, 177, 31, 40, true},
 {"BayDoor_01", "WindowMullion_1", 0.2, 3, 0.12, -75.60000000000001, 9.5, -11.81, 98, 107, 109, false},
 {"BayDoor_01", "WindowMullion_2", 0.2, 3, 0.12, -72.0, 9.5, -11.81, 98, 107, 109, false},
 {"BayDoor_01", "WindowMullion_3", 0.2, 3, 0.12, -68.4, 9.5, -11.81, 98, 107, 109, false},
 {"BayDoor_01", "WindowMullion_4", 0.2, 3, 0.12, -64.8, 9.5, -11.81, 98, 107, 109, false},
 {"BayDoor_01", "RollerSeam_0", 18, 0.1, 0.08, -70.2, 4, -11.98, 57, 62, 65, false},
 {"BayDoor_01", "RollerSeam_1", 18, 0.1, 0.08, -70.2, 15, -11.98, 57, 62, 65, false},
 {"BayDoor_01", "RollerSeam_2", 18, 0.1, 0.08, -70.2, 19, -11.98, 57, 62, 65, false},
 {"BayDoor_01", "RollerSeam_3", 18, 0.1, 0.08, -70.2, 23, -11.98, 57, 62, 65, false},
 {"BayDoor_01", "RollerSeam_4", 18, 0.1, 0.08, -70.2, 27, -11.98, 57, 62, 65, false},
 {"Site", "Exit_1_Edge_-1", 0.35, 0.05, 35, -79.60000000000001, 0.105, -34.5, 234, 186, 51, false},
 {"Site", "Exit_1_Edge_1", 0.35, 0.05, 35, -60.800000000000004, 0.105, -34.5, 234, 186, 51, false},
 {"Site", "Exit_1_End", 19.15, 0.05, 0.35, -70.2, 0.105, -52, 234, 186, 51, false},
 {"BayDoor_02", "LowerPanel", 18.0, 8, 0.9000000000000004, -47.400000000000006, 4.0, -11.45, 177, 31, 40, true},
 {"BayDoor_02", "WindowBand", 18.0, 3, 0.5999999999999996, -47.400000000000006, 9.5, -11.399999999999999, 39, 65, 71, true},
 {"BayDoor_02", "UpperPanel", 18.0, 19, 0.9000000000000004, -47.400000000000006, 20.5, -11.45, 177, 31, 40, true},
 {"BayDoor_02", "WindowMullion_1", 0.2, 3, 0.12, -52.800000000000004, 9.5, -11.81, 98, 107, 109, false},
 {"BayDoor_02", "WindowMullion_2", 0.2, 3, 0.12, -49.2, 9.5, -11.81, 98, 107, 109, false},
 {"BayDoor_02", "WindowMullion_3", 0.2, 3, 0.12, -45.60000000000001, 9.5, -11.81, 98, 107, 109, false},
 {"BayDoor_02", "WindowMullion_4", 0.2, 3, 0.12, -42.00000000000001, 9.5, -11.81, 98, 107, 109, false},
 {"BayDoor_02", "RollerSeam_0", 18, 0.1, 0.08, -47.400000000000006, 4, -11.98, 57, 62, 65, false},
 {"BayDoor_02", "RollerSeam_1", 18, 0.1, 0.08, -47.400000000000006, 15, -11.98, 57, 62, 65, false},
 {"BayDoor_02", "RollerSeam_2", 18, 0.1, 0.08, -47.400000000000006, 19, -11.98, 57, 62, 65, false},
 {"BayDoor_02", "RollerSeam_3", 18, 0.1, 0.08, -47.400000000000006, 23, -11.98, 57, 62, 65, false},
 {"BayDoor_02", "RollerSeam_4", 18, 0.1, 0.08, -47.400000000000006, 27, -11.98, 57, 62, 65, false},
 {"Site", "Exit_2_Edge_-1", 0.35, 0.05, 35, -56.800000000000004, 0.105, -34.5, 234, 186, 51, false},
 {"Site", "Exit_2_Edge_1", 0.35, 0.05, 35, -38.00000000000001, 0.105, -34.5, 234, 186, 51, false},
 {"Site", "Exit_2_End", 19.15, 0.05, 0.35, -47.400000000000006, 0.105, -52, 234, 186, 51, false},
 {"BayDoor_03", "LowerPanel", 18.0, 8, 0.9000000000000004, -24.6, 4.0, -11.45, 177, 31, 40, true},
 {"BayDoor_03", "WindowBand", 18.0, 3, 0.5999999999999996, -24.6, 9.5, -11.399999999999999, 39, 65, 71, true},
 {"BayDoor_03", "UpperPanel", 18.0, 19, 0.9000000000000004, -24.6, 20.5, -11.45, 177, 31, 40, true},
 {"BayDoor_03", "WindowMullion_1", 0.2, 3, 0.12, -30.0, 9.5, -11.81, 98, 107, 109, false},
 {"BayDoor_03", "WindowMullion_2", 0.2, 3, 0.12, -26.400000000000002, 9.5, -11.81, 98, 107, 109, false},
 {"BayDoor_03", "WindowMullion_3", 0.2, 3, 0.12, -22.8, 9.5, -11.81, 98, 107, 109, false},
 {"BayDoor_03", "WindowMullion_4", 0.2, 3, 0.12, -19.200000000000003, 9.5, -11.81, 98, 107, 109, false},
 {"BayDoor_03", "RollerSeam_0", 18, 0.1, 0.08, -24.6, 4, -11.98, 57, 62, 65, false},
 {"BayDoor_03", "RollerSeam_1", 18, 0.1, 0.08, -24.6, 15, -11.98, 57, 62, 65, false},
 {"BayDoor_03", "RollerSeam_2", 18, 0.1, 0.08, -24.6, 19, -11.98, 57, 62, 65, false},
 {"BayDoor_03", "RollerSeam_3", 18, 0.1, 0.08, -24.6, 23, -11.98, 57, 62, 65, false},
 {"BayDoor_03", "RollerSeam_4", 18, 0.1, 0.08, -24.6, 27, -11.98, 57, 62, 65, false},
 {"Site", "Exit_3_Edge_-1", 0.35, 0.05, 35, -34.0, 0.105, -34.5, 234, 186, 51, false},
 {"Site", "Exit_3_Edge_1", 0.35, 0.05, 35, -15.200000000000001, 0.105, -34.5, 234, 186, 51, false},
 {"Site", "Exit_3_End", 19.15, 0.05, 0.35, -24.6, 0.105, -52, 234, 186, 51, false},
 {"BayDoor_04", "LowerPanel", 18.0, 8, 0.9000000000000004, -1.7999999999999972, 4.0, -11.45, 177, 31, 40, true},
 {"BayDoor_04", "WindowBand", 18.0, 3, 0.5999999999999996, -1.7999999999999972, 9.5, -11.399999999999999, 39, 65, 71, true},
 {"BayDoor_04", "UpperPanel", 18.0, 19, 0.9000000000000004, -1.7999999999999972, 20.5, -11.45, 177, 31, 40, true},
 {"BayDoor_04", "WindowMullion_1", 0.2, 3, 0.12, -7.1999999999999975, 9.5, -11.81, 98, 107, 109, false},
 {"BayDoor_04", "WindowMullion_2", 0.2, 3, 0.12, -3.599999999999997, 9.5, -11.81, 98, 107, 109, false},
 {"BayDoor_04", "WindowMullion_3", 0.2, 3, 0.12, 3.552713678800501e-15, 9.5, -11.81, 98, 107, 109, false},
 {"BayDoor_04", "WindowMullion_4", 0.2, 3, 0.12, 3.600000000000003, 9.5, -11.81, 98, 107, 109, false},
 {"BayDoor_04", "RollerSeam_0", 18, 0.1, 0.08, -1.7999999999999972, 4, -11.98, 57, 62, 65, false},
 {"BayDoor_04", "RollerSeam_1", 18, 0.1, 0.08, -1.7999999999999972, 15, -11.98, 57, 62, 65, false},
 {"BayDoor_04", "RollerSeam_2", 18, 0.1, 0.08, -1.7999999999999972, 19, -11.98, 57, 62, 65, false},
 {"BayDoor_04", "RollerSeam_3", 18, 0.1, 0.08, -1.7999999999999972, 23, -11.98, 57, 62, 65, false},
 {"BayDoor_04", "RollerSeam_4", 18, 0.1, 0.08, -1.7999999999999972, 27, -11.98, 57, 62, 65, false},
 {"Site", "Exit_4_Edge_-1", 0.35, 0.05, 35, -11.199999999999998, 0.105, -34.5, 234, 186, 51, false},
 {"Site", "Exit_4_Edge_1", 0.35, 0.05, 35, 7.600000000000003, 0.105, -34.5, 234, 186, 51, false},
 {"Site", "Exit_4_End", 19.15, 0.05, 0.35, -1.7999999999999972, 0.105, -52, 234, 186, 51, false},
 {"Signage", "HallSign", 91, 5.8, 0.5, -36, 34.1, -12.3, 177, 31, 40, false},
 {"Administration", "Base", 48, 3, 64, 36.0, 1.5, 20.0, 225, 222, 209, true},
 {"Administration", "MidSpandrel", 48, 7, 64, 36.0, 19.5, 20.0, 225, 222, 209, true},
 {"Administration", "UpperSpandrel", 48, 3, 64, 36.0, 36.5, 20.0, 225, 222, 209, true},
 {"Administration", "Roof", 48, 2, 64, 36.0, 39.0, 20.0, 57, 62, 65, true},
 {"Administration", "FrontF1Pier0", 1, 13, 1, 12.5, 9.5, -11.5, 225, 222, 209, true},
 {"Administration", "FrontF1Glass0", 11, 13, 0.3800000000000008, 18.5, 9.5, -11.690000000000001, 39, 65, 71, true},
 {"Administration", "FrontF1Pier1", 1, 13, 1, 24.5, 9.5, -11.5, 225, 222, 209, true},
 {"Administration", "FrontF1Glass1", 11, 13, 0.3800000000000008, 30.5, 9.5, -11.690000000000001, 39, 65, 71, true},
 {"Administration", "FrontF1Pier2", 1, 13, 1, 36.5, 9.5, -11.5, 225, 222, 209, true},
 {"Administration", "FrontF1Glass2", 11, 13, 0.3800000000000008, 42.5, 9.5, -11.690000000000001, 39, 65, 71, true},
 {"Administration", "FrontF1Pier3", 1, 13, 1, 48.5, 9.5, -11.5, 225, 222, 209, true},
 {"Administration", "FrontF1Glass3", 11, 13, 0.3800000000000008, 54.5, 9.5, -11.690000000000001, 39, 65, 71, true},
 {"Administration", "RearF1Pier0", 1, 13, 1, 12.5, 9.5, 51.5, 225, 222, 209, true},
 {"Administration", "RearF1Glass0", 11, 13, 0.38000000000000256, 18.5, 9.5, 51.31, 39, 65, 71, true},
 {"Administration", "RearF1Pier1", 1, 13, 1, 24.5, 9.5, 51.5, 225, 222, 209, true},
 {"Administration", "RearF1Glass1", 11, 13, 0.38000000000000256, 30.5, 9.5, 51.31, 39, 65, 71, true},
 {"Administration", "RearF1Pier2", 1, 13, 1, 36.5, 9.5, 51.5, 225, 222, 209, true},
 {"Administration", "RearF1Glass2", 11, 13, 0.38000000000000256, 42.5, 9.5, 51.31, 39, 65, 71, true},
 {"Administration", "RearF1Pier3", 1, 13, 1, 48.5, 9.5, 51.5, 225, 222, 209, true},
 {"Administration", "RearF1Glass3", 11, 13, 0.38000000000000256, 54.5, 9.5, 51.31, 39, 65, 71, true},
 {"Administration", "LeftF1Pier0", 1, 13, 1.0, 12.5, 9.5, -10.5, 225, 222, 209, true},
 {"Administration", "LeftF1Glass0", 0.5, 13, 14.5, 12.4, 9.5, -2.75, 39, 65, 71, true},
 {"Administration", "LeftF1Pier1", 1, 13, 1.0, 12.5, 9.5, 5.0, 225, 222, 209, true},
 {"Administration", "LeftF1Glass1", 0.5, 13, 14.5, 12.4, 9.5, 12.75, 39, 65, 71, true},
 {"Administration", "LeftF1Pier2", 1, 13, 1.0, 12.5, 9.5, 20.5, 225, 222, 209, true},
 {"Administration", "LeftF1Glass2", 0.5, 13, 14.5, 12.4, 9.5, 28.25, 39, 65, 71, true},
 {"Administration", "LeftF1Pier3", 1, 13, 1.0, 12.5, 9.5, 36.0, 225, 222, 209, true},
 {"Administration", "LeftF1Glass3", 0.5, 13, 14.5, 12.4, 9.5, 43.75, 39, 65, 71, true},
 {"Administration", "RightF1Pier0", 1, 13, 1.0, 59.5, 9.5, -10.5, 225, 222, 209, true},
 {"Administration", "RightF1Glass0", 0.5, 13, 14.5, 59.4, 9.5, -2.75, 39, 65, 71, true},
 {"Administration", "RightF1Pier1", 1, 13, 1.0, 59.5, 9.5, 5.0, 225, 222, 209, true},
 {"Administration", "RightF1Glass1", 0.5, 13, 14.5, 59.4, 9.5, 12.75, 39, 65, 71, true},
 {"Administration", "RightF1Pier2", 1, 13, 1.0, 59.5, 9.5, 20.5, 225, 222, 209, true},
 {"Administration", "RightF1Glass2", 0.5, 13, 14.5, 59.4, 9.5, 28.25, 39, 65, 71, true},
 {"Administration", "RightF1Pier3", 1, 13, 1.0, 59.5, 9.5, 36.0, 225, 222, 209, true},
 {"Administration", "RightF1Glass3", 0.5, 13, 14.5, 59.4, 9.5, 43.75, 39, 65, 71, true},
 {"Administration", "FrontF2Pier0", 1, 12, 1, 12.5, 29.0, -11.5, 225, 222, 209, true},
 {"Administration", "FrontF2Glass0", 11, 12, 0.3800000000000008, 18.5, 29.0, -11.690000000000001, 39, 65, 71, true},
 {"Administration", "FrontF2Pier1", 1, 12, 1, 24.5, 29.0, -11.5, 225, 222, 209, true},
 {"Administration", "FrontF2Glass1", 11, 12, 0.3800000000000008, 30.5, 29.0, -11.690000000000001, 39, 65, 71, true},
 {"Administration", "FrontF2Pier2", 1, 12, 1, 36.5, 29.0, -11.5, 225, 222, 209, true},
 {"Administration", "FrontF2Glass2", 11, 12, 0.3800000000000008, 42.5, 29.0, -11.690000000000001, 39, 65, 71, true},
 {"Administration", "FrontF2Pier3", 1, 12, 1, 48.5, 29.0, -11.5, 225, 222, 209, true},
 {"Administration", "FrontF2Glass3", 11, 12, 0.3800000000000008, 54.5, 29.0, -11.690000000000001, 39, 65, 71, true},
 {"Administration", "RearF2Pier0", 1, 12, 1, 12.5, 29.0, 51.5, 225, 222, 209, true},
 {"Administration", "RearF2Glass0", 11, 12, 0.38000000000000256, 18.5, 29.0, 51.31, 39, 65, 71, true},
 {"Administration", "RearF2Pier1", 1, 12, 1, 24.5, 29.0, 51.5, 225, 222, 209, true},
 {"Administration", "RearF2Glass1", 11, 12, 0.38000000000000256, 30.5, 29.0, 51.31, 39, 65, 71, true},
 {"Administration", "RearF2Pier2", 1, 12, 1, 36.5, 29.0, 51.5, 225, 222, 209, true},
 {"Administration", "RearF2Glass2", 11, 12, 0.38000000000000256, 42.5, 29.0, 51.31, 39, 65, 71, true},
 {"Administration", "RearF2Pier3", 1, 12, 1, 48.5, 29.0, 51.5, 225, 222, 209, true},
 {"Administration", "RearF2Glass3", 11, 12, 0.38000000000000256, 54.5, 29.0, 51.31, 39, 65, 71, true},
 {"Administration", "LeftF2Pier0", 1, 12, 1.0, 12.5, 29.0, -10.5, 225, 222, 209, true},
 {"Administration", "LeftF2Glass0", 0.5, 12, 14.5, 12.4, 29.0, -2.75, 39, 65, 71, true},
 {"Administration", "LeftF2Pier1", 1, 12, 1.0, 12.5, 29.0, 5.0, 225, 222, 209, true},
 {"Administration", "LeftF2Glass1", 0.5, 12, 14.5, 12.4, 29.0, 12.75, 39, 65, 71, true},
 {"Administration", "LeftF2Pier2", 1, 12, 1.0, 12.5, 29.0, 20.5, 225, 222, 209, true},
 {"Administration", "LeftF2Glass2", 0.5, 12, 14.5, 12.4, 29.0, 28.25, 39, 65, 71, true},
 {"Administration", "LeftF2Pier3", 1, 12, 1.0, 12.5, 29.0, 36.0, 225, 222, 209, true},
 {"Administration", "LeftF2Glass3", 0.5, 12, 14.5, 12.4, 29.0, 43.75, 39, 65, 71, true},
 {"Administration", "RightF2Pier0", 1, 12, 1.0, 59.5, 29.0, -10.5, 225, 222, 209, true},
 {"Administration", "RightF2Glass0", 0.5, 12, 14.5, 59.4, 29.0, -2.75, 39, 65, 71, true},
 {"Administration", "RightF2Pier1", 1, 12, 1.0, 59.5, 29.0, 5.0, 225, 222, 209, true},
 {"Administration", "RightF2Glass1", 0.5, 12, 14.5, 59.4, 29.0, 12.75, 39, 65, 71, true},
 {"Administration", "RightF2Pier2", 1, 12, 1.0, 59.5, 29.0, 20.5, 225, 222, 209, true},
 {"Administration", "RightF2Glass2", 0.5, 12, 14.5, 59.4, 29.0, 28.25, 39, 65, 71, true},
 {"Administration", "RightF2Pier3", 1, 12, 1.0, 59.5, 29.0, 36.0, 225, 222, 209, true},
 {"Administration", "RightF2Glass3", 0.5, 12, 14.5, 59.4, 29.0, 43.75, 39, 65, 71, true},
 {"Administration", "EntryLeft", 3, 18, 2, 29.5, 9.0, -12.0, 225, 222, 209, true},
 {"Administration", "EntryRight", 3, 18, 2, 44.5, 9.0, -12.0, 225, 222, 209, true},
 {"Administration", "EntryDoor", 12, 14, 0.40000000000000036, 37.0, 7.0, -12.600000000000001, 39, 65, 71, true},
 {"Administration", "EntryDoorMullion", 0.25, 14, 0.3, 37, 7, -12.95, 98, 107, 109, true},
 {"Administration", "EntryHandle_35.7", 0.2, 3, 0.35, 35.7, 7, -13.15, 98, 107, 109, false},
 {"Administration", "EntryHandle_38.3", 0.2, 3, 0.35, 38.3, 7, -13.15, 98, 107, 109, false},
 {"Administration", "EntryCanopy", 30, 1.5, 12, 37, 18.5, -18, 177, 31, 40, true},
 {"Administration", "CanopyCap", 30, 0.35, 12, 37, 19.425, -18, 57, 62, 65, false},
 {"Administration", "CanopyColumn_24", 1.2, 17.75, 1.2, 24, 8.875, -21, 225, 222, 209, true},
 {"Administration", "CanopyColumn_50", 1.2, 17.75, 1.2, 50, 8.875, -21, 225, 222, 209, true},
 {"Administration", "FrontRedBand", 48, 2, 0.3, 36, 21, -12.15, 177, 31, 40, false},
 {"Administration", "UpperRedBand", 48, 2, 0.3, 36, 36.5, -12.15, 177, 31, 40, false},
 {"TrainingTower", "BackWall", 24, 85, 2, 72.0, 42.5, 19.0, 225, 222, 209, true},
 {"TrainingTower", "LeftWall", 2, 85, 30, 61.0, 42.5, 3.0, 225, 222, 209, true},
 {"TrainingTower", "RightWall", 2, 85, 30, 83.0, 42.5, 3.0, 225, 222, 209, true},
 {"TrainingTower", "FrontLeftPier", 5, 85, 2, 64.5, 42.5, -11.0, 225, 222, 209, true},
 {"TrainingTower", "FrontRightPier", 5, 85, 2, 79.5, 42.5, -11.0, 225, 222, 209, true},
 {"TowerLevel_01", "Floor", 20, 1, 30, 72.0, 0.5, 3.0, 225, 222, 209, true},
 {"TowerLevel_01", "FrontSill", 10, 2, 2, 72.0, 2.0, -11.0, 225, 222, 209, true},
 {"TowerLevel_01", "FrontLintel", 10, 1, 2, 72.0, 13.5, -11.0, 225, 222, 209, true},
 {"TowerLevel_01", "SafetyTopRail", 10, 0.3, 0.3, 72, 6, -11.5, 234, 186, 51, true},
 {"TowerLevel_01", "SafetyMidRail", 10, 0.2, 0.25, 72, 4.6, -11.5, 234, 186, 51, true},
 {"TowerLevel_01", "SafetyUpright_0", 0.22, 3, 0.22, 67.3, 4.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_01", "SafetyUpright_1", 0.22, 3, 0.22, 69.65, 4.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_01", "SafetyUpright_2", 0.22, 3, 0.22, 72, 4.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_01", "SafetyUpright_3", 0.22, 3, 0.22, 74.35, 4.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_01", "SafetyUpright_4", 0.22, 3, 0.22, 76.7, 4.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_02", "Floor", 20, 1, 30, 72.0, 14.5, 3.0, 225, 222, 209, true},
 {"TowerLevel_02", "FrontSill", 10, 2, 2, 72.0, 16.0, -11.0, 225, 222, 209, true},
 {"TowerLevel_02", "FrontLintel", 10, 1, 2, 72.0, 27.5, -11.0, 225, 222, 209, true},
 {"TowerLevel_02", "SafetyTopRail", 10, 0.3, 0.3, 72, 20, -11.5, 234, 186, 51, true},
 {"TowerLevel_02", "SafetyMidRail", 10, 0.2, 0.25, 72, 18.6, -11.5, 234, 186, 51, true},
 {"TowerLevel_02", "SafetyUpright_0", 0.22, 3, 0.22, 67.3, 18.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_02", "SafetyUpright_1", 0.22, 3, 0.22, 69.65, 18.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_02", "SafetyUpright_2", 0.22, 3, 0.22, 72, 18.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_02", "SafetyUpright_3", 0.22, 3, 0.22, 74.35, 18.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_02", "SafetyUpright_4", 0.22, 3, 0.22, 76.7, 18.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_03", "Floor", 20, 1, 30, 72.0, 28.5, 3.0, 225, 222, 209, true},
 {"TowerLevel_03", "FrontSill", 10, 2, 2, 72.0, 30.0, -11.0, 225, 222, 209, true},
 {"TowerLevel_03", "FrontLintel", 10, 1, 2, 72.0, 41.5, -11.0, 225, 222, 209, true},
 {"TowerLevel_03", "SafetyTopRail", 10, 0.3, 0.3, 72, 34, -11.5, 234, 186, 51, true},
 {"TowerLevel_03", "SafetyMidRail", 10, 0.2, 0.25, 72, 32.6, -11.5, 234, 186, 51, true},
 {"TowerLevel_03", "SafetyUpright_0", 0.22, 3, 0.22, 67.3, 32.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_03", "SafetyUpright_1", 0.22, 3, 0.22, 69.65, 32.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_03", "SafetyUpright_2", 0.22, 3, 0.22, 72, 32.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_03", "SafetyUpright_3", 0.22, 3, 0.22, 74.35, 32.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_03", "SafetyUpright_4", 0.22, 3, 0.22, 76.7, 32.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_04", "Floor", 20, 1, 30, 72.0, 42.5, 3.0, 225, 222, 209, true},
 {"TowerLevel_04", "FrontSill", 10, 2, 2, 72.0, 44.0, -11.0, 225, 222, 209, true},
 {"TowerLevel_04", "FrontLintel", 10, 1, 2, 72.0, 55.5, -11.0, 225, 222, 209, true},
 {"TowerLevel_04", "SafetyTopRail", 10, 0.3, 0.3, 72, 48, -11.5, 234, 186, 51, true},
 {"TowerLevel_04", "SafetyMidRail", 10, 0.2, 0.25, 72, 46.6, -11.5, 234, 186, 51, true},
 {"TowerLevel_04", "SafetyUpright_0", 0.22, 3, 0.22, 67.3, 46.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_04", "SafetyUpright_1", 0.22, 3, 0.22, 69.65, 46.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_04", "SafetyUpright_2", 0.22, 3, 0.22, 72, 46.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_04", "SafetyUpright_3", 0.22, 3, 0.22, 74.35, 46.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_04", "SafetyUpright_4", 0.22, 3, 0.22, 76.7, 46.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_05", "Floor", 20, 1, 30, 72.0, 56.5, 3.0, 225, 222, 209, true},
 {"TowerLevel_05", "FrontSill", 10, 2, 2, 72.0, 58.0, -11.0, 225, 222, 209, true},
 {"TowerLevel_05", "FrontLintel", 10, 1, 2, 72.0, 69.5, -11.0, 225, 222, 209, true},
 {"TowerLevel_05", "SafetyTopRail", 10, 0.3, 0.3, 72, 62, -11.5, 234, 186, 51, true},
 {"TowerLevel_05", "SafetyMidRail", 10, 0.2, 0.25, 72, 60.6, -11.5, 234, 186, 51, true},
 {"TowerLevel_05", "SafetyUpright_0", 0.22, 3, 0.22, 67.3, 60.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_05", "SafetyUpright_1", 0.22, 3, 0.22, 69.65, 60.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_05", "SafetyUpright_2", 0.22, 3, 0.22, 72, 60.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_05", "SafetyUpright_3", 0.22, 3, 0.22, 74.35, 60.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_05", "SafetyUpright_4", 0.22, 3, 0.22, 76.7, 60.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_06", "Floor", 20, 1, 30, 72.0, 70.5, 3.0, 225, 222, 209, true},
 {"TowerLevel_06", "FrontSill", 10, 2, 2, 72.0, 72.0, -11.0, 225, 222, 209, true},
 {"TowerLevel_06", "FrontLintel", 10, 1, 2, 72.0, 83.5, -11.0, 225, 222, 209, true},
 {"TowerLevel_06", "SafetyTopRail", 10, 0.3, 0.3, 72, 76, -11.5, 234, 186, 51, true},
 {"TowerLevel_06", "SafetyMidRail", 10, 0.2, 0.25, 72, 74.6, -11.5, 234, 186, 51, true},
 {"TowerLevel_06", "SafetyUpright_0", 0.22, 3, 0.22, 67.3, 74.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_06", "SafetyUpright_1", 0.22, 3, 0.22, 69.65, 74.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_06", "SafetyUpright_2", 0.22, 3, 0.22, 72, 74.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_06", "SafetyUpright_3", 0.22, 3, 0.22, 74.35, 74.5, -11.5, 234, 186, 51, true},
 {"TowerLevel_06", "SafetyUpright_4", 0.22, 3, 0.22, 76.7, 74.5, -11.5, 234, 186, 51, true},
 {"TrainingTower", "CrownBase", 24, 2, 32, 72.0, 85.0, 4.0, 225, 222, 209, true},
 {"TrainingTower", "RedCrown", 24, 5, 32, 72.0, 88.5, 4.0, 177, 31, 40, true},
 {"TrainingTower", "RoofCap", 24, 2, 32, 72.0, 92.0, 4.0, 57, 62, 65, true},
 {"TrainingTower", "Antenna", 0.3, 3, 0.3, 72, 94.5, 4, 98, 107, 109, false},
 {"Service", "Cabinet", 3, 7, 12, -86, 3.5, 27, 57, 62, 65, true},
 {"Service", "FencePost_19", 0.25, 8, 0.25, -87.7, 4, 19, 98, 107, 109, true},
 {"Service", "FencePost_35", 0.25, 8, 0.25, -87.7, 4, 35, 98, 107, 109, true},
 {"Service", "FenceTop", 0.25, 0.25, 16, -87.7, 7.9, 27, 98, 107, 109, true},
 {"Service", "FenceBar_20", 0.12, 7.5, 0.12, -87.7, 3.75, 20, 98, 107, 109, false},
 {"Service", "FenceBar_22", 0.12, 7.5, 0.12, -87.7, 3.75, 22, 98, 107, 109, false},
 {"Service", "FenceBar_24", 0.12, 7.5, 0.12, -87.7, 3.75, 24, 98, 107, 109, false},
 {"Service", "FenceBar_26", 0.12, 7.5, 0.12, -87.7, 3.75, 26, 98, 107, 109, false},
 {"Service", "FenceBar_28", 0.12, 7.5, 0.12, -87.7, 3.75, 28, 98, 107, 109, false},
 {"Service", "FenceBar_30", 0.12, 7.5, 0.12, -87.7, 3.75, 30, 98, 107, 109, false},
 {"Service", "FenceBar_32", 0.12, 7.5, 0.12, -87.7, 3.75, 32, 98, 107, 109, false},
 {"Service", "FenceBar_34", 0.12, 7.5, 0.12, -87.7, 3.75, 34, 98, 107, 109, false},
}
function Builder.Build(parent, options)
 options = options or {}
 local model = Instance.new("Model")
 model.Name = "LargeCity_EmberlineResponseHQ_P4"
 model:SetAttribute("LayoutId", "LC-45")
 model:SetAttribute("Phase", 4)
 model:SetAttribute("QualityGateB", "Pending")
 model:SetAttribute("BuildRevision", "Emberline-P4-v1")
 local pivot = Instance.new("Part")
 pivot.Name = "GroundPivot"
 pivot.Size = Vector3.new(0.1, 0.1, 0.1)
 pivot.CFrame = CFrame.new()
 pivot.Transparency = 1
 pivot.Anchored = true
 pivot.CanCollide = false
 pivot.CanTouch = false
 pivot.CanQuery = false
 pivot.Parent = model
 model.PrimaryPart = pivot
 local groups = {}
 for _, d in ipairs(Parts) do
  if not groups[d[1]] then
   local group = Instance.new("Model")
   group.Name = d[1]
   group.Parent = model
   groups[d[1]] = group
  end
  local p = Instance.new("Part")
  p.Name = d[2]
  p.Size = Vector3.new(d[3], d[4], d[5])
  p.CFrame = CFrame.new(d[6], d[7], d[8])
  p.Color = Color3.fromRGB(d[9], d[10], d[11])
  p.Material = Enum.Material.SmoothPlastic
  p.Anchored = true
  p.CanCollide = d[12]
  p.TopSurface = Enum.SurfaceType.Smooth
  p.BottomSurface = Enum.SurfaceType.Smooth
  p.Parent = groups[d[1]]
 end
 local gui = Instance.new("SurfaceGui")
 gui.Name = "StationName"
 gui.Face = Enum.NormalId.Front
 gui.CanvasSize = Vector2.new(1400, 100)
 gui.Parent = groups.Signage.HallSign
 local label = Instance.new("TextLabel")
 label.Name = "Title"
 label.Size = UDim2.fromScale(1, 1)
 label.BackgroundTransparency = 1
 label.Text = "EMBERLINE RESPONSE HQ"
 label.TextColor3 = Color3.new(1,1,1)
 label.Font = Enum.Font.ArialBold
 label.TextScaled = true
 label.Parent = gui
 model.Parent = parent
 model:PivotTo(options.GroundCFrame or CFrame.new())
 return model
end
return Builder
