-- Phase 3 technical breakdown for the approved Sovereign-V Apex visual target.
local Color3 = Color3 or {
	fromRGB = function(r, g, b)
		return {R = r / 255, G = g / 255, B = b / 255}
	end,
}

return {
	SchemaVersion = 1,
	AssetName = "Sovereign-V Apex",
	AssetId = "Sovereign_V_Apex",
	AssetClass = "Guardian Apex Hunter And Battlefield-Control Platform",
	Tier = 5,
	City = "Megacity",
	PipelinePhase = 6,
	Status = "StandardAnimationReview",
	QualityGateA = "Approved",
	QualityGateB = "Approved",
	QualityGateC = "Pending",

	Role = {
		Primary = "ActiveKaijuHuntAndBattlefieldControl",
		FleetBaseChassis = "Aegis-III Interceptor",
		CombatRead = "MonumentalPrecisionHunter",
		MaxHealth = 32000000,
		BarrierPoints = 8000000,
		WalkSpeed = 20,
		DetectionRange = 320,
		AttackRange = 240,
	},

	Scale = {
		HeightStuds = 72,
		ShoulderWidthStuds = 36,
		StanceWidthStuds = 16,
		TorsoWidthStuds = 25,
		HeadEnvelopeStuds = {X = 7.5, Y = 4.2, Z = 5.5},
		FootEnvelopeStuds = {X = 8.0, Y = 3.6, Z = 11.0},
		ApexLanceHousingLengthStuds = 18,
		ApexLanceEnergyBladeLengthStuds = 20,
		DroneEnvelopeStuds = {X = 6.0, Y = 4.5, Z = 8.5},
		DroneWingFoldedWidthStuds = 36,
		DroneWingDeployedSpanStuds = 74,
		DroneWingRiseStuds = 20,
		ChestEmblemWidthStuds = 11,
	},

	Palette = {
		Chassis = Color3.fromRGB(15, 15, 22),
		Body = Color3.fromRGB(38, 35, 48),
		Armor = Color3.fromRGB(105, 101, 119),
		Accent = Color3.fromRGB(184, 45, 250),
		ChargeHot = Color3.fromRGB(234, 157, 255),
		DarkMetal = Color3.fromRGB(13, 12, 18),
	},

	Dressing = {
		Style = "ApexNightPredator",
		GeometryChangesAllowed = false,
		PermanentLights = 0,
		PermanentParticleEmitters = 0,
		TransientParticlePreview = true,
		TransientEmitterLifetimeSeconds = 1.75,
		EnergyChannel = "SovereignViolet",
		DroneReferenceIds = {
			LeftDroneInner = "L1",
			RightDroneInner = "R1",
			LeftDroneOuter = "L2",
			RightDroneOuter = "R2",
			LeftDroneLower = "L3",
			RightDroneLower = "R3",
		},
	},

	RequiredAssemblies = {
		"Rig",
		"Armor",
		"Systems",
		"Equipment",
		"Hitboxes",
		"Metadata",
		"FleetHeadAndFeet",
		"ApexLance",
		"HunterDroneWings",
		"SovereignLock",
	},

	Identity = {
		HeadCount = 1,
		HeadPlacement = "Centered",
		HeadArchitecture = "LowArmoredFleetWedge",
		VisorCount = 1,
		VisorType = "ContinuousRecessedHorizontalSlit",
		ChestEmblem = "LargeCentralVioletV",
		ChestEmblemMustRemainUnobstructed = true,
		FootArchitecture = "FleetTwoToeBlockAndReinforcedHeel",
		DerivedFromAegis = true,
		ReadableFleetJointDiscs = true,
	},

	Equipment = {
		ApexLance = {
			Count = 1,
			Mount = "LeftForearm",
			ReplacesArm = false,
			OppositeHandRemainsFree = true,
			MechanicalHousingPermanent = true,
			EnergyBladeRuntimeVisible = true,
			RestForwardAngleDegrees = 30,
			ShaftBeginsNearElbow = true,
			MustClearGroundAtRest = true,
			IndependentAimCorrection = true,
			SupportsThrust = true,
			SupportsLateralCut = true,
			SupportsFocusedBeam = true,
			MustClearLeftDroneWing = true,
		},
		HunterDroneWings = {
			DroneCount = 6,
			DronesPerSide = 3,
			Mount = "RearUpperTorso",
			Formation = "RaisedMechanicalBatClaws",
			DroneHeadShape = "ArmoredPredatorWedge",
			DroneSensor = "RecessedVioletTwinSlashes",
			DroneForwardMandibles = 2,
			UsesMembrane = false,
			UsesFeathers = false,
			Foldable = true,
			Launchable = true,
			Recoverable = true,
			EachDroneHasPhysicalDock = true,
			EachDroneHasIndividualHitbox = true,
			LeftDockNames = {"LeftDroneInner", "LeftDroneOuter", "LeftDroneLower"},
			RightDockNames = {"RightDroneInner", "RightDroneOuter", "RightDroneLower"},
		},
		SovereignLock = {
			PhysicalEnergySource = "ChestVAndHipNodes",
			RuntimeAnchors = "SixDeployedHunterDrones",
			RuntimeField = "SixPointKaijuControlPrism",
			BarrierPoints = 8000000,
			PermanentFieldVisible = false,
			SlowsMovementWithoutFullStun = true,
			MaintainsCounterplay = true,
		},
	},

	Rig = {
		Standard = "GuardianFleetRigV1",
		ForwardAxis = "-Z",
		RequiredBaseControlParts = 16,
		RequiredBaseMotors = 15,
		Proportioning = "AegisDerivedNonUniformApexVariant",
		EquipmentControls = {
			"ApexLanceControl",
			"LeftDroneWingRootControl",
			"RightDroneWingRootControl",
			"LeftDroneInnerControl",
			"LeftDroneOuterControl",
			"LeftDroneLowerControl",
			"RightDroneInnerControl",
			"RightDroneOuterControl",
			"RightDroneLowerControl",
		},
		RequiredTotalControlParts = 25,
		RequiredTotalMotors = 24,
	},

	Hitboxes = {
		"Head",
		"Torso",
		"LeftArm",
		"RightArm",
		"LeftLeg",
		"RightLeg",
		"ApexLance",
		"LeftDroneInner",
		"LeftDroneOuter",
		"LeftDroneLower",
		"RightDroneInner",
		"RightDroneOuter",
		"RightDroneLower",
		"SovereignLockCore",
	},

	GeometryRules = {
		NoCoplanarOverlappingFaces = true,
		MinimumSurfaceOffsetStuds = 0.04,
		NoZFighting = true,
		UseLargeBeveledArmorPlates = true,
		AvoidTinyGreebles = true,
		ReadableJointDiscs = true,
		BuildFromPreviousFleetChassis = true,
		ExactlyOneCenteredFleetHead = true,
		FleetHeadAndFeetMustRemainRecognizable = true,
		ExactlySixDrones = true,
		ThreeDronesPerWing = true,
		NoWingMembraneOrFeathers = true,
		NoFloatingEquipment = true,
		ApexLanceMustNotObstructChestEmblem = true,
		DroneWingsMustClearHeadAndShoulders = true,
	},

	PerformanceBudget = {
		MaxVisibleParts = 190,
		MaxGameplayHitboxes = 14,
		PermanentParticleEmitters = 0,
		PermanentLights = 0,
		PerPartScripts = 0,
		MaxSimultaneousActiveDrones = 6,
		MaxTransientLockSegments = 12,
		MaxSimultaneousLanceBeams = 1,
	},

	AnimationRequirements = {
		ReuseFleetLocomotion = true,
		ApexHunterLocomotionVariant = true,
		DroneWingsFoldWithLocomotion = true,
		DroneWingInertia = {
			IdleDegrees = 2.2,
			MaximumRunningFoldDegrees = 8,
			MaximumTurnLagDegrees = 9,
			ResponseByPair = {Inner = 0.28, Middle = 0.62, Outer = 1.0},
		},
		DroneWingDeployLaunchRecover = true,
		ApexLanceThrustAndCut = true,
		ApexLanceAimChargeBeam = true,
		SovereignLockSixPointDeploy = true,
		DamageStaggerDefeatReset = true,
	},

	VisualTarget = {
		Version = 4,
		Approved = true,
		Description = "A monumental Aegis-derived precision hunter with the fleet's low visor head, broad two-toe feet, one compact forearm Apex Lance, and exactly six Hunter Drones carried on raised skeletal bat-claw arms, three per side.",
	},
}
