"""Phase 5 decoration from the approved P4 geometry. No remote assets.
Run python3 tools/build_residential_dressing.py [--preview].
"""
from pathlib import Path
import runpy,sys,json,math,xml.etree.ElementTree as E
ROOT=Path(__file__).resolve().parents[1]
preview='--preview' in sys.argv
saved=sys.argv;sys.argv=[sys.argv[0]]
b=runpy.run_path(str(ROOT/'tools/build_residential.py'));sys.argv=saved
parts=b['parts'];base=list(parts);palette=b['PALETTE'];part=b['part'];beam=b['beam'];DOC=b['DOC'];MOD=b['MOD'];DEST=b['DEST']
palette.update(warm=(255,226,173),leaf=(67,109,64),leaflight=(100,139,78),soil=(80,67,48),wood=(117,91,60),railglass=(80,112,118))
lights=[]
def add(g,n,size,pos,col='metal',collide=False,rz=0,shape='Block',rx=0,transparency=0):
    part(g,n,size,pos,col,collide,rz,rx)
    parts[-1].update(shape=shape,transparency=transparency)
# Infill stays between the approved top rail and slab, behind upright outer faces.
for p in base:
    n=p['name'];w,h,d=p['size'];x,y,z=p['pos']
    if n.endswith('Rail') or n.endswith('Return'):
        if w>d:sz=(max(.1,w-.4),2.6,.14)
        else:sz=(.14,2.6,max(.1,d-.4))
        add(p['group'],n+'Glass',sz,(x,y-1.5,z),'railglass',transparency=.48)
# Sparse balcony planters alternate to preserve the facade rhythm.
def planted(g,n,x,y,z,w=7,d=2.5):
    add(g,n+'Trough',(w,1.4,d),(x,y+.7,z),'sand')
    add(g,n+'Soil',(w-.4,.15,d-.4),(x,y+1.48,z),'soil')
    for i in range(2):
        add(g,n+f'Leaves{i}',(w/2-.2,1.7,d-.3),(x+(i-.5)*w/2,y+2.1,z),'leaf' if i else 'leaflight',rz=(i-.5)*.12)
for i in range(10):
    y=32+i*16;g=f'Residence{i+1:02}'
    planted(g,'BalconyPlanter',-27 if i%2==0 else 15,y+2.2,-27)
# Lower roof and both setbacks keep clear paths, planted ends only.
for i,(x,z,w,d) in enumerate([(-49,-22,6,10),(37,-22,6,10),(-44,38,8,5),(32,38,8,5)]):
    planted('PodiumTerrace',f'Planter{i}',x,32.3,z,w,d)
for g,y,front,back,xs in [('Setback01',192.3,-22,30,[-26,14]),('Setback02',208.3,-18,26,[-22,10])]:
    for i,x in enumerate(xs):
        planted(g,f'FrontPlanter{i}',x,y,front,6,2)
        planted(g,f'RearPlanter{i}',x,y,back,6,2)
# Ground planters are already hollow; add soil, shrubs and three small tree crowns.
for j,(x,z,w,d) in enumerate([(-40,-43,28,10),(27,-43,24,10),(-58,5,8,48)]):
    add('Site',f'Soil{j}',(w-2,.2,d-2),(x,1.4,z),'soil')
    for i in range(5):
        px=x+(i-2)*(w-5)/5 if w>d else x
        pz=z if w>d else z+(i-2)*(d-5)/5
        add('Site',f'Shrub{j}_{i}',(3,2.4,3),(px,2.5,pz),'leaflight' if i%2 else 'leaf',rz=(i%3-1)*.12)
    add('Site',f'TreeTrunk{j}',(.7,7,.7),(x,5,z),'wood')
    for k,(dx,dy,dz) in enumerate([(-1,0,0),(1,0,.5),(0,1.5,-.3)]):
        add('Site',f'TreeCrown{j}_{k}',(4,4,4),(x+dx,8+dy,z+dz),'leaf' if k%2 else 'leaflight',shape='Ball')
# Warm entry lights and canopy downlights, no light on every balcony.
for i,x in enumerate([-24,12]):
    add('Entrance',f'WallBase{i}',(.9,3,.5),(x,9,-32.45),'roof')
    add('Entrance',f'WallLens{i}',(.6,2.5,.2),(x,9,-32.85),'warm')
    lights.append(('Entrance',f'WallLens{i}',.7,16,(255,226,173)))
for i,x in enumerate([-18,6]):
    add('Entrance',f'CanopyLens{i}',(1.2,.15,1.2),(x,14.4,-38),'warm')
    lights.append(('Entrance',f'CanopyLens{i}',.6,14,(255,226,173)))
# Slope-aligned yellow ramp markings rest above the sloping road surface.
angle=math.atan2(8,48)
for i,x in enumerate([44.5,61.5]):
    add('Garage',f'RampEdge{i}',(.3,.04,math.hypot(48,8)),(x,-4+.045*math.cos(angle),-24+.045*math.sin(angle)),'yellow',rx=angle)
for i,z in enumerate([-38,-26,-14,-2]):
    surface=-(z+48)/6
    add('Garage',f'RampLightBase{i}',(.4,.9,1.8),(44.25,surface+1.5,z),'roof')
    add('Garage',f'RampLens{i}',(.15,.6,1.3),(44.55,surface+1.5,z),'warm')
    lights.append(('Garage',f'RampLens{i}',.45,10,(255,226,173)))
for i in range(8):add('Garage',f'GateSlat{i}',(17.6,.15,.14),(53,-7+i*1.1,14.84),'metal')
# Louvers outside the compact roof block, cap height remains exactly232.
for side,z in [('Front',-4.2),('Rear',12.2)]:
    for i in range(7):add('RoofEquipment',f'{side}Louver{i}',(20,.22,.18),(-6,224.7+i*.85,z),'metal')
extra=parts[len(base):]
materials={'concrete':('Concrete',816),'ground':('Concrete',816),'glass':('Glass',1568),'roof':('Metal',1088),'metal':('Metal',1088),'blue':('SmoothPlastic',272),'yellow':('SmoothPlastic',272),'warm':('Neon',288),'beacon':('Neon',288),'leaf':('Grass',1280),'leaflight':('Grass',1280),'soil':('Ground',1360),'sand':('Concrete',816),'wood':('Wood',512),'railglass':('Glass',1568)}
# Lua dressing is repeatable, preserving approved structural geometry and original pivot.
def lua(x):
    if isinstance(x,(list,tuple)):return '{'+','.join(lua(v) for v in x)+'}'
    return json.dumps(x)
rows=['-- Generated by tools/build_residential_dressing.py. Gate B user-approved, P5 review pending.','local Dressing = {}','local Parts = {']
for p in extra:rows.append(lua([p['group'],p['name'],*p['size'],*p['pos'],*palette[p['color']],p['collide'],p['rz'],p['shape'],materials.get(p['color'],('SmoothPlastic',272))[0],p.get('rx',0),p.get('transparency',0)])+',')
rows+=['}','local BaseMaterials = {']
for p in base:rows.append(lua([p['group'],p['name'],materials.get(p['color'],('SmoothPlastic',272))[0]])+',')
rows+=['}','local Lights = '+lua(lights),'''
function Dressing.Apply(model)
 assert(model.PrimaryPart, "Residential dressing requires the original ground pivot")
 local old = model:FindFirstChild("ResidentialDressing")
 if old then old:Destroy() end
 local root = Instance.new("Folder"); root.Name = "ResidentialDressing"; root.Parent = model
 local origin = model:GetPivot(); local groups = {}
 for _,d in ipairs(BaseMaterials) do
  local g = model:FindFirstChild(d[1]); local p = g and g:FindFirstChild(d[2])
  if p then p.Material = Enum.Material[d[3]] end
 end
 for _,d in ipairs(Parts) do
  if not groups[d[1]] then local g = Instance.new("Model"); g.Name = d[1]; g.Parent = root; groups[d[1]] = g end
  local p = Instance.new("Part"); p.Name = d[2]; p.Size = Vector3.new(d[3],d[4],d[5])
  p.CFrame = origin * CFrame.new(d[6],d[7],d[8]) * CFrame.Angles(0,0,d[13]) * CFrame.Angles(d[16],0,0)
  p.Color = Color3.fromRGB(d[9],d[10],d[11]); p.CanCollide = d[12]; p.Anchored = true
  p.Shape = Enum.PartType[d[14]]; p.Material = Enum.Material[d[15]]; p.Transparency = d[17]
  p.TopSurface = Enum.SurfaceType.Smooth; p.BottomSurface = Enum.SurfaceType.Smooth
  p.Parent = groups[d[1]]
 end
 for _,d in ipairs(Lights) do
  local l = Instance.new("PointLight"); l.Name = "FixtureLight"; l.Brightness = d[3]; l.Range = d[4]
  l.Color = Color3.fromRGB(d[5][1],d[5][2],d[5][3]); l.Shadows = false; l.Parent = groups[d[1]][d[2]]
 end
 model.Name = "LargeCity_ResidentialTower_P5"; model:SetAttribute("Phase",5)
 model:SetAttribute("QualityGateB","ApprovedByUser"); model:SetAttribute("DressingReview","Pending")
 model:SetAttribute("BuildRevision","Residential-P5-v1")
 return model
end
return Dressing
''']
(MOD/'LargeCityResidentialDressing.lua').write_text('\n'.join(rows))
# Extend the static P4 XML, using exactly the same definitions as the Lua dressing.
root=b['root'];model=b['model'];item=b['item'];val=b['val'];vec=b['vec']
model.find("Properties/string[@name='Name']").text='LargeCity_ResidentialTower_P5'
lookup={(p['group'],p['name']):p for p in base}
for group in model.findall('Item'):
    for it in group.findall('Item'):
        gn=group.find("Properties/string[@name='Name']").text;n=it.find("Properties/string[@name='Name']").text
        if (gn,n) in lookup:it.find("Properties/token[@name='Material']").text=str(materials.get(lookup[(gn,n)]['color'],('SmoothPlastic',272))[1])
dr,_=item(model,'Folder','ResidentialDressing');groups={};owners={}
for p in extra:
    if p['group'] not in groups:groups[p['group']]=item(dr,'Model',p['group'])[0]
    it,pr=item(groups[p['group']],'Part',p['name']);owners[p['group'],p['name']]=it
    vec(pr,'size',p['size']);c=E.SubElement(pr,'CoordinateFrame',name='CFrame')
    for axis,n in zip('XYZ',p['pos']):E.SubElement(c,axis).text=str(n)
    a=p['rz'];rx=p.get('rx',0);ca,sa,cr,sr=math.cos(a),math.sin(a),math.cos(rx),math.sin(rx);rot=((ca,-sa*cr,sa*sr),(sa,ca*cr,-ca*sr),(0,sr,cr))
    for i in range(3):
        for j in range(3):E.SubElement(c,f'R{i}{j}').text=str(rot[i][j])
    col=palette[p['color']];val(pr,'Color3uint8','Color3uint8',(255<<24)|(col[0]<<16)|(col[1]<<8)|col[2])
    for k,v in [('Anchored',True),('CanCollide',p['collide'])]:val(pr,'bool',k,v)
    for k,v in [('Material',materials.get(p['color'],('SmoothPlastic',272))[1]),('TopSurface',0),('BottomSurface',0),('shape',0 if p['shape']=='Ball' else 1)]:val(pr,'token',k,v)
    val(pr,'float','Transparency',p.get('transparency',0))
def rgb(pr,name,col):
    c=E.SubElement(pr,'Color3',name=name)
    for axis,v in zip('RGB',col):E.SubElement(c,axis).text=str(v/255)
def u2(pr,name,x,y):
    c=E.SubElement(pr,'UDim2',name=name)
    for k,v in [('XS',x),('XO',0),('YS',y),('YO',0)]:E.SubElement(c,k).text=str(v)
for g,n,bright,ran,col in lights:
    _,pr=item(owners[g,n],'PointLight','FixtureLight')
    val(pr,'float','Brightness',bright);val(pr,'float','Range',ran);val(pr,'bool','Shadows',False);rgb(pr,'Color',col)
for it in model.findall("Item[@class='Folder']/Item[@class='StringValue']"):
    n=it.find("Properties/string[@name='Name']").text
    if n in {'Phase','GateB','Revision'}:it.find("Properties/string[@name='Value']").text={'Phase':'5','GateB':'ApprovedByUser 2026-09-27','Revision':'Residential-P5-v1'}[n]
path=DEST/'LargeCityResidentialTower_P5.rbxmx';E.ElementTree(root).write(path,encoding='utf-8',xml_declaration=True)
# Export and bounds tests, plus protection of the approved facade spacing.
for p in extra:
    bb=b['bounds'](p);assert bb[0][0]>=-64 and bb[0][1]<=64 and bb[2][0]>=-56 and bb[2][1]<=56 and bb[1][1]<=232,p
assert len({(p['group'],p['name']) for p in extra})==len(extra)
t=E.parse(path);assert len(t.findall('.//Item[@class="Part"]'))==len(parts)+1
assert len(t.findall('.//Item[@class="PointLight"]'))==8
assert len(t.findall('.//Item[@class="SurfaceGui"]'))==0
assert not t.findall('.//Item[@class="Script"]')
assert all(n.find("Properties/bool[@name='Shadows']").text=='false' for n in t.findall('.//Item[@class="PointLight"]'))
assert all(p['size'][1]==2.6 and p['transparency']==.48 for p in extra if p['color']=='railglass')
report=dict(revision='Residential-P5-v1',base_parts=len(base)+1,dressing_parts=len(extra),total_parts=len(parts)+1,point_lights=8,shadow_lights=0,gate_b='ApprovedByUser 2026-09-27',p5_review='Pending',studio_import='Pending',garage_gate='Static; no animation',checks=['P4 facade checks rerun','plot and 232-stud height respected','XML count','8 lights / no remote assets','no scripts or remote assets'])
(DOC/'dressing-checks.json').write_text(json.dumps(report,indent=2)+'\n')
if preview:
    # Reuse the existing technical projection. Rounded parts show their bounding volumes.
    s=(ROOT/'tools/build_residential.py').read_text();s=s[s.index("if '--preview'"):s.rindex('print(json.dumps(report))')]
    s=s.replace('RESIDENTIAL TOWER | Phase 4','RESIDENTIAL TOWER | Phase 5').replace('Gate B offen','Dressing zur Abnahme').replace('geometry-review.png','dressing-review.png')
    s=s.replace('Symbole, Schrift, Materialtexturen und Lichtwirkung erst in Studio sichtbar.','Technische Huellkoerper; Glastransparenz, Rundungen und Lichtwirkung erst in Studio sichtbar.')
    env=dict(b);env.update(parts=parts,PALETTE=palette,report=report,sys=sys);exec(s,env)
print(json.dumps(report))
