"""Generate the runtime placement manifest from the reviewable JSON plan."""
from pathlib import Path
import json
r=Path(__file__).resolve().parents[1]
def lua(v):
 if v is None:return 'nil'
 if isinstance(v,bool):return str(v).lower()
 if isinstance(v,(int,float)):return str(v)
 if isinstance(v,str):return json.dumps(v,ensure_ascii=False)
 if isinstance(v,list):return '{'+','.join(map(lua,v))+'}'
 return '{'+','.join('['+lua(k)+']='+lua(val) for k,val in v.items())+'}'
data=json.loads((r/'docs/city/city-plan.json').read_text())
# Merge grid cells into non-overlapping axis-aligned rectangles.
def rectangles(bounds,regions,include):
 x0,z0,x1,z1=bounds
 xs=sorted({x0,x1,*[max(x0,min(x1,v)) for q in regions for v in (q[0],q[2])]})
 zs=sorted({z0,z1,*[max(z0,min(z1,v)) for q in regions for v in (q[1],q[3])]})
 finished=[];active={}
 for za,zb in zip(zs,zs[1:]):
  spans=[];start=None
  for xa,xb in zip(xs,xs[1:]):
   x,z=(xa+xb)/2,(za+zb)/2
   occupied=any(a<x<c and b<z<d for a,b,c,d in regions)
   if occupied==include:
    if start is None:start=xa
   elif start is not None:spans.append((start,xa));start=None
  if start is not None:spans.append((start,xs[-1]))
  new={}
  for span in spans:
   if span in active:new[span]=[span[0],active[span][1],span[1],zb]
   else:new[span]=[span[0],za,span[1],zb]
  finished += [q for span,q in active.items() if span not in new]
  active=new
 return finished+list(active.values())
plots=[[p['x']-p['world_width']/2,p['z']-p['world_depth']/2,p['x']+p['world_width']/2,p['z']+p['world_depth']/2] for p in data['plots']]
roads=[]
for _,x1,z1,x2,z2,w in data['roads']:
 roads.append([min(x1,x2)-(w/2 if x1==x2 else 0),min(z1,z2)-(w/2 if z1==z2 else 0),max(x1,x2)+(w/2 if x1==x2 else 0),max(z1,z2)+(w/2 if z1==z2 else 0)])
data['ground_surfaces']=rectangles(data.get("ground_bounds",[-1380,-1450,1830,1450]),plots,False)
data['road_surfaces']=rectangles(data.get("ground_bounds",[-1380,-1450,1830,1450]),roads,True)
(r/'src/ReplicatedStorage/TrenchbornAssetWorkshop/LargeCityPlan.lua').write_text('-- Generated by tools/build_city_plan.py; edit docs/city/city-plan.json.\nreturn '+lua(data)+'\n')
print('Generated runtime plan: 21 masters / 54 buildings / 1 reserve.')
